#Database details
database:
  dsn: mysql://root:@localhost/cms_innodb
  prefix: cms_

#Should we be in debug mode?
debug: true

#Places to look for classes when autoloading
#(app/models will be autoloaded later on)
class_autoload:
  - lib/cmsms/classes
